"""add used flag to settings_tokens

Revision ID: 4cf91fb152a0
Revises: 6757e07bff0c
Create Date: 2026-01-17 09:46:10.553959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf91fb152a0'
down_revision: Union[str, Sequence[str], None] = '6757e07bff0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings_tokens', sa.Column('used', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings_tokens', 'used')
    # ### end Alembic commands ###
