"""add settings token

Revision ID: 6757e07bff0c
Revises: 2772148afa59
Create Date: 2026-01-11 15:03:08.946837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6757e07bff0c'
down_revision: Union[str, Sequence[str], None] = '2772148afa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_tokens_id'), 'settings_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_settings_tokens_token'), 'settings_tokens', ['token'], unique=True)
    op.add_column('message_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('message_logs', 'quote',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'message_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_logs', type_='foreignkey')
    op.alter_column('message_logs', 'quote',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('message_logs', 'user_id')
    op.drop_index(op.f('ix_settings_tokens_token'), table_name='settings_tokens')
    op.drop_index(op.f('ix_settings_tokens_id'), table_name='settings_tokens')
    op.drop_table('settings_tokens')
    # ### end Alembic commands ###
